words = [
    "Akhmetgaleev",
    "Containerfile",
    "Ildar",
    "MKNOD",
    "PULSEAUDIO",
    "Podman",
    "akhilman",
    "archlinux",
    "buildah",
    "chmod",
    "chown",
    "cli",
    "dbus",
    "dnf",
    "getent",
    "groupadd",
    "opensuse",
    "pacman",
    "pipewire",
    "setuptools",
    "tinkerbox",
    "udp",
    "whoami",
    "xdg",
    "zypper",
]
