description = "Default Tinkerbox image profile. Support images: alpine, archlinux, debian, fedora, opensuse/tumbleweed and ubuntu. Other images with apk, apt, dnf, pacman or zypper may work but not tested."

from = "debian"
cmd = ["sudo", "/usr/local/sbin/entrypoint.sh"]

[environment]
CONTAINER_UID = "@{UID}"
CONTAINER_GID = "@{GID}"
CONTAINER_USER = "@{CONTAINER_USER}"
CONTAINER_HOME = "@{CONTAINER_HOME}"

[[add]]
src = "default-entrypoint.sh"
dst = "/usr/local/sbin/entrypoint.sh"
chown = "root"
chmod = "755"

[[add]]
src = "default-bootstrap.sh"
dst = "/usr/local/sbin/bootstrap.sh"
chown = "root"
chmod = "755"

[[run]]
command = ["/bin/sh", "/usr/local/sbin/bootstrap.sh"]
user = "root"
